// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from 'eslint-plugin-storybook';

import prettier from 'eslint-config-prettier';
import { includeIgnoreFile } from '@eslint/compat';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import { fileURLToPath } from 'node:url';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

const gitignorePath = fileURLToPath(new URL('./.gitignore', import.meta.url));

export default ts.config(
  includeIgnoreFile(gitignorePath),
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs.recommended,
  prettier,
  ...svelte.configs.prettier,
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node }
    },
    rules: {
      // typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
      // see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
      'no-undef': 'off',
      // Playwright's fixture API requires object destructuring in the first
      // parameter even when no fixtures are consumed: test.beforeEach(({}, testInfo) => ...)
      'no-empty-pattern': ['error', { allowObjectPatternsAsParameters: true }],
      // Underscore prefix marks intentionally-unused bindings (existing codebase convention)
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          ignoreRestSiblings: true
        }
      ],
      // This codebase builds collections inside $derived.by/getters and uses
      // copy-on-write reassignment for $state collections — both patterns are
      // already reactive without SvelteMap/SvelteSet/SvelteDate. The rule cannot
      // distinguish those from in-place mutation of reactive state (the actual
      // footgun), so current hits are audited false positives (June 2026,
      // see .claude/plans/lint-cleanup-rich-harris-report.md).
      'svelte/prefer-svelte-reactivity': 'off'
    }
  },
  {
    // src/lib is published library code: hrefs/gotos there render
    // consumer-supplied URLs and may not even run inside SvelteKit (the README
    // documents plain-DOM mounting), so SvelteKit's resolve() does not apply.
    // The rule stays on for src/routes (the dev playground app).
    files: ['src/lib/**'],
    rules: {
      'svelte/no-navigation-without-resolve': 'off'
    }
  },
  {
    files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        extraFileExtensions: ['.svelte'],
        parser: ts.parser,
        svelteConfig
      }
    }
  },
  storybook.configs['flat/recommended'],
  {
    // MSW-generated worker script — regenerated by `msw init`, never hand-edited
    ignores: ['static/mockServiceWorker.js']
  },
  {
    files: ['src/lib/**/*.ts', 'src/lib/**/*.svelte'],
    ignores: ['src/lib/utils/logger.ts', 'src/lib/mocks/**'],
    rules: {
      'no-console': 'warn'
    }
  }
);
