/**
 * GENERATED by scripts/generate-token-aliases.mjs from styles/tokens.css and
 * styles/base.css. Do not edit by hand; run `pnpm run generate:token-aliases`.
 *
 * Alias tokens: declarations whose value reads another --fd-* token. A custom
 * property holding var() is resolved where it is declared, so a skin scoped to
 * an editor root must redeclare the aliases that depend on the tokens it sets.
 * Keys omit the --fd- prefix.
 */

/** Light/base aliases (:root). */
export const LIGHT_ALIASES: Readonly<Record<string, string>> = {
  'canvas-bg': 'var(--fd-background)',
  'caption-node-bg': 'var(--fd-foreground)',
  'caption-node-fg': 'var(--fd-background)',
  'control-radius': 'var(--fd-radius-lg)',
  'elevation-float': 'var(--fd-shadow-md)',
  'float-border': 'var(--fd-border)',
  'handle-offset': 'calc(-1 * var(--fd-handle-size) / 2)',
  'interrupt-avatar-size': 'var(--fd-size-avatar)',
  'interrupt-badge-completed-bg': 'var(--fd-primary-muted)',
  'interrupt-badge-completed-text': 'var(--fd-primary)',
  'interrupt-btn-min-height': 'var(--fd-size-btn-min)',
  'interrupt-btn-primary-bg':
    'linear-gradient(135deg, var(--fd-primary) 0%, var(--fd-primary-hover) 100%)',
  'interrupt-btn-primary-bg-hover':
    'linear-gradient(135deg, var(--fd-primary-hover) 0%, var(--fd-primary-hover) 100%)',
  'interrupt-btn-secondary-bg': 'var(--fd-muted)',
  'interrupt-btn-secondary-border': 'var(--fd-border)',
  'interrupt-btn-secondary-text': 'var(--fd-foreground)',
  'interrupt-cancelled-avatar': 'var(--fd-muted-foreground)',
  'interrupt-cancelled-bg': 'linear-gradient(135deg, var(--fd-muted) 0%, var(--fd-subtle) 100%)',
  'interrupt-cancelled-border': 'var(--fd-muted-foreground)',
  'interrupt-cancelled-text': 'var(--fd-muted-foreground)',
  'interrupt-cancelled-text-light': 'var(--fd-muted-foreground)',
  'interrupt-completed-avatar': 'var(--fd-primary)',
  'interrupt-completed-bg':
    'linear-gradient(135deg, var(--fd-info-muted) 0%, var(--fd-primary-muted) 100%)',
  'interrupt-completed-border': 'var(--fd-primary)',
  'interrupt-completed-text': 'var(--fd-primary-hover)',
  'interrupt-completed-text-light': 'var(--fd-primary)',
  'interrupt-error-avatar': 'var(--fd-error)',
  'interrupt-error-bg':
    'linear-gradient(135deg, var(--fd-error-muted) 0%, var(--fd-error-muted) 100%)',
  'interrupt-error-border': 'var(--fd-error)',
  'interrupt-error-text': 'var(--fd-error-hover)',
  'interrupt-error-text-light': 'var(--fd-error)',
  'interrupt-font-error': 'var(--fd-text-xsm)',
  'interrupt-font-message': 'var(--fd-text-md)',
  'interrupt-font-mono': 'var(--fd-font-mono)',
  'interrupt-line-height': 'var(--fd-leading-normal)',
  'interrupt-pending-avatar': 'var(--fd-warning)',
  'interrupt-pending-bg':
    'linear-gradient(135deg, var(--fd-warning-muted) 0%, var(--fd-warning-muted) 100%)',
  'interrupt-pending-border': 'var(--fd-warning)',
  'interrupt-pending-text': 'var(--fd-warning-hover)',
  'interrupt-pending-text-light': 'var(--fd-warning-hover)',
  'interrupt-selected-confirm-bg': 'var(--fd-interrupt-btn-primary-bg)',
  'interrupt-selected-confirm-border': 'var(--fd-primary-hover)',
  'interrupt-selected-decline-bg': 'var(--fd-error-muted)',
  'interrupt-selected-decline-border': 'var(--fd-error)',
  'interrupt-selected-decline-text': 'var(--fd-error)',
  'interrupt-spinner-size': 'var(--fd-size-spinner)',
  'node-bg': 'var(--fd-card)',
  'node-header-bg': 'var(--fd-header)',
  'node-header-divider-color': 'var(--fd-border-muted)',
  'node-radius': 'var(--fd-radius-xl)',
  'node-shadow': 'var(--fd-shadow-md)',
  'node-shadow-hover': 'var(--fd-shadow-lg)',
  'note-border': 'var(--fd-node-border)',
  'note-border-hover': 'var(--fd-node-border-hover)',
  'panel-bg': 'var(--fd-background)',
  'playground-icon-btn-size': 'var(--fd-size-icon-btn)',
  'radius-bubble': 'var(--fd-radius-xl)',
  'radius-surface': 'var(--fd-radius-lg)',
  'review-font-mono': 'var(--fd-interrupt-font-mono)',
  'review-font-size-error': 'var(--fd-interrupt-font-error)',
  'review-font-size-html-toggle': 'var(--fd-text-2xs)',
  'review-font-size-message': 'var(--fd-interrupt-font-message)',
  'review-line-height': 'var(--fd-interrupt-line-height)',
  'review-line-height-content': 'var(--fd-leading-relaxed)',
  'review-space-lg': 'var(--fd-space-lg)',
  'review-space-md': 'var(--fd-space-sm)',
  'review-space-sm': 'var(--fd-space-2xs)',
  'review-toggle-height': 'var(--fd-size-icon-btn)',
  'sidebar-category-color': 'var(--fd-muted-foreground)',
  'sidebar-flat-item-color': 'var(--fd-foreground)',
  'status-completed': 'var(--fd-success)',
  'status-completed-soft': 'var(--fd-success-muted)',
  'status-failed': 'var(--fd-error)',
  'status-failed-soft': 'var(--fd-error-muted)',
  'status-running': 'var(--fd-info)',
  'status-running-soft': 'var(--fd-info-muted)',
  'status-skipped': 'var(--fd-muted-foreground)',
  'status-skipped-soft': 'var(--fd-muted)',
  'status-waiting': 'var(--fd-warning)',
  'status-waiting-soft': 'var(--fd-warning-muted)',
  'text-body': 'var(--fd-text-base)',
  'text-meta': 'var(--fd-text-xs)'
};

/** Dark overrides ([data-theme='dark']): aliases, plus literal dark values of light aliases. */
export const DARK_ALIASES: Readonly<Record<string, string>> = {
  'caption-node-bg': 'var(--fd-foreground)',
  'caption-node-fg': 'var(--fd-background)',
  'interrupt-badge-completed-bg': 'var(--fd-primary-muted)',
  'interrupt-badge-completed-text': 'var(--fd-primary)',
  'interrupt-btn-secondary-bg': 'var(--fd-secondary)',
  'interrupt-btn-secondary-border': 'var(--fd-border)',
  'interrupt-btn-secondary-text': 'var(--fd-foreground)',
  'interrupt-selected-decline-bg': 'rgba(248, 113, 113, 0.15)'
};
